### ISSUE TITLE
Can't compile using php version 5.6.30 and jansson version 2.10

### ISSUE THREAD

**Issue by rockmetoo** [stellartech/phpjansson#1]
`/usr/local/src/phpjansson-master/jansson.c:1034:40: error: too few arguments to function ‘zend_register_internal_class_ex’
     jansson_constructor_exception_ce = zend_register_internal_class_ex(
                                        ^
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from ./php_jansson.h:22,
                 from /usr/local/src/phpjansson-master/jansson.c:23:
/usr/include/php/20131226/Zend/zend_API.h:280:28: note: declared here
 ZEND_API zend_class_entry *zend_register_internal_class_ex(zend_class_entry *class_entry, zend_class_entry *pare
                            ^
Makefile:181: recipe for target 'jansson.lo' failed
make: *** [jansson.lo] Error 1`

**Comment by A-j-K** [comment]
Are you using the 5.6.x tagged release? Master is for PHP 7.1.x

See https://github.com/stellartech/phpjansson/tree/v5.6.x

**Comment by rockmetoo** [comment]
Thanks for your reply.

Would you please tell me which version is for 5.6.x?

**Comment by rockmetoo** [comment]
Sorry! I got it. Thanks.

**Comment by A-j-K** [comment]
Please note, I'm not really maintaining the 5.6.x these days. But the 7.1.x has all the features and some extras (like serialize/unserialize to strings). I know switching up to 7.1.x can be hard if you have a legacy project but I highly recommend 7.1.x if you can :)

**Comment by rockmetoo** [comment]
roger that. Thanks by the way.
